
-- TO CREATE THE SQL PROCEDURE
--1、CONNECT TO THE DATABASE
--2、ENTER THE COMMAND "DB2 -TD@ -VF TRANSPRO2H.SQL"

-- TO CALL THE SQL PROCEDURE FROM THE COMMAND LINE:
--1、CONNECT TO THE DATABASE 
--2、ENTER THE FOLLOWING COMMAND :
-- "DB2 CALL TRANSPRODATATOHISTORY"

--如果存在同名的存储过程则删除
DROP PROCEDURE TRANSPRODATATOHISTORY@

--创建存储过程
CREATE PROCEDURE TRANSPRODATATOHISTORY
	LANGUAGE SQL
		BEGIN
			
			DECLARE PROINSTID VARCHAR(20);
			DECLARE V_NUMBER INTEGER DEFAULT 0;
			
			DECLARE C1 CURSOR FOR 
				SELECT PROCESSINSTID FROM WFPROCESSINST WHERE CURRENTSTATE='7' OR CURRENTSTATE='8';
			
			DECLARE CONTINUE HANDLER FOR NOT FOUND SET V_NUMBER=1;
			
			OPEN C1;
			FETCH_LOOP:
			LOOP
				FETCH C1 INTO PROINSTID;
				
				IF(V_NUMBER <> 0) THEN
					LEAVE FETCH_LOOP;
				END IF;
				
				--工作项表 WF_H_WORKITEM
				INSERT INTO WF_H_WORKITEM (WORKITEMID, WORKITEMNAME, WORKITEMTYPE, WORKITEMDESC, CURRENTSTATE, PARTICIPANT, PARTINAME, PRIORITY, ISTIMEOUT, LIMITNUM, LIMITNUMDESC, CREATETIME, STARTTIME, ENDTIME, FINALTIME, REMINDTIME, ACTIONURL, PROCESSINSTID, ACTIVITYINSTID, STATESLIST, TIMEOUTNUM, TIMEOUTNUMDESC, PROCESSINSTNAME, ACTIVITYINSTNAME, PROCESSDEFID, PROCESSDEFNAME, PROCESSCHNAME, ACTIVITYDEFID, ASSISTANT, ASSISTANTNAME, BIZSTATE, ALLOWAGENT, ROOTPROCINSTID, ACTIONMASK, URLTYPE, DEALRESULT, DEALOPINION, EXTEND1, EXTEND2, EXTEND3, EXTEND4, EXTEND5, EXTEND6, EXTEND7, CATALOGUUID, CATALOGNAME, TENANT_ID, ALERTFLAG, PRESSNUM, TASKPOOLID, BELONG, UPDATETIME, ACCEPTTIME) SELECT WORKITEMID, WORKITEMNAME, WORKITEMTYPE, WORKITEMDESC, CURRENTSTATE, PARTICIPANT, PARTINAME, PRIORITY, ISTIMEOUT, LIMITNUM, LIMITNUMDESC, CREATETIME, STARTTIME, ENDTIME, FINALTIME, REMINDTIME, ACTIONURL, PROCESSINSTID, ACTIVITYINSTID, STATESLIST, TIMEOUTNUM, TIMEOUTNUMDESC, PROCESSINSTNAME, ACTIVITYINSTNAME, PROCESSDEFID, PROCESSDEFNAME, PROCESSCHNAME, ACTIVITYDEFID, ASSISTANT, ASSISTANTNAME, BIZSTATE, ALLOWAGENT, ROOTPROCINSTID, ACTIONMASK, URLTYPE, DEALRESULT, DEALOPINION, EXTEND1, EXTEND2, EXTEND3, EXTEND4, EXTEND5, EXTEND6, EXTEND7, CATALOGUUID, CATALOGNAME, TENANT_ID, ALERTFLAG, PRESSNUM, TASKPOOLID, BELONG, UPDATETIME, ACCEPTTIME FROM WFWORKITEM WHERE PROCESSINSTID = PROINSTID;
				DELETE FROM WFWORKITEM WHERE PROCESSINSTID = PROINSTID;
				
				--连线控制表 WF_H_TRANSCTRL
				INSERT INTO WF_H_TRANSCTRL (TRANSCTRLID, SRCACTDEFID, DESTACTDEFID, SRCACTDEFNAME, DESTACTDEFNAME, LASTTRANSTIME, TRANSWEIGHT, PROCESSINSTID, EXTEND1, TENANT_ID) SELECT TRANSCTRLID, SRCACTDEFID, DESTACTDEFID, SRCACTDEFNAME, DESTACTDEFNAME, LASTTRANSTIME, TRANSWEIGHT, PROCESSINSTID, EXTEND1, TENANT_ID FROM WFTRANSCTRL WHERE PROCESSINSTID = PROINSTID;
				DELETE FROM WFTRANSCTRL WHERE PROCESSINSTID = PROINSTID;
				
				--连线表 WF_H_TRANSITION
				INSERT INTO WF_H_TRANSITION (TRANSITIONID, TRANSITIONTYPE, CAUSEACTINSTID, CAUSEACTINSTNAME, RESULTACTINSTID, RESULTACTINSTNAME, SRCACTDEFID, DESTACTDEFID, SRCACTDEFNAME, DESTACTDEFNAME, TRANSTIME, PROCESSINSTID, EXTEND1, TENANT_ID) SELECT TRANSITIONID, TRANSITIONTYPE, CAUSEACTINSTID, CAUSEACTINSTNAME, RESULTACTINSTID, RESULTACTINSTNAME, SRCACTDEFID, DESTACTDEFID, SRCACTDEFNAME, DESTACTDEFNAME, TRANSTIME, PROCESSINSTID, EXTEND1, TENANT_ID FROM WFTRANSITION WHERE PROCESSINSTID = PROINSTID;
				DELETE FROM WFTRANSITION WHERE PROCESSINSTID = PROINSTID;
				
				--活动实例表 WF_H_ACTIVITYINST
				INSERT INTO WF_H_ACTIVITYINST (ACTIVITYINSTID, ACTIVITYINSTNAME, ACTIVITYINSTDESC, ACTIVITYTYPE, CURRENTSTATE, PRIORITY, CREATETIME, STARTTIME, ENDTIME, FINALTIME, SUBPROCESSID, ACTIVITYDEFID, PROCESSINSTID, ROLLBACKFLAG, EXTEND1, EXTEND2, EXTEND3, EXTEND4, EXTEND5, EXTEND6, EXTEND7, CATALOGUUID, CATALOGNAME, TENANT_ID, RELATEDATA, UPDATETIME) SELECT ACTIVITYINSTID, ACTIVITYINSTNAME, ACTIVITYINSTDESC, ACTIVITYTYPE, CURRENTSTATE, PRIORITY, CREATETIME, STARTTIME, ENDTIME, FINALTIME, SUBPROCESSID, ACTIVITYDEFID, PROCESSINSTID, ROLLBACKFLAG, EXTEND1, EXTEND2, EXTEND3, EXTEND4, EXTEND5, EXTEND6, EXTEND7, CATALOGUUID, CATALOGNAME, TENANT_ID, RELATEDATA, UPDATETIME FROM WFACTIVITYINST WHERE PROCESSINSTID = PROINSTID;
				DELETE FROM WFACTIVITYINST WHERE PROCESSINSTID = PROINSTID;
				
				--流程属性表 WF_H_PROCESSINSTATTR
				INSERT INTO WF_H_PROCESSINSTATTR (PROCESSINSTID, ATTRIBUTE, EXTEND1, EXTEND2, EXTEND3, TENANT_ID) SELECT PROCESSINSTID, ATTRIBUTE, EXTEND1, EXTEND2, EXTEND3, TENANT_ID FROM WFPROCESSINSTATTR WHERE PROCESSINSTID ＝ PROINSTID; 
				DELETE FROM WFPROCESSINSTATTR WHERE PROCESSINSTID = PROINSTID;
				
				--流程实例表 WF_H_PROCESSINST
				INSERT INTO WF_H_PROCESSINST (PROCESSINSTID, PROCESSINSTNAME, PROCESSINSTDESC, CREATOR, OWNER, CURRENTSTATE, PRIORITY, RELATEDATA, RELATEDATAVCHR, LIMITNUM, LIMITNUMDESC, CREATETIME, STARTTIME, ENDTIME, FINALTIME, REMINDTIME, PARENTPROCID, PARENTACTID, PROCESSDEFID, ISTIMEOUT, TIMEOUTNUM, TIMEOUTNUMDESC, UPDATEVERSION, PROCESSDEFNAME, EXTEND1, EXTEND2, EXTEND3, EXTEND4, EXTEND5, EXTEND6, EXTEND7, CATALOGUUID, CATALOGNAME, TENANT_ID, BELONG, ALERTFLAG, ERRORFLAG, UPDATETIME) SELECT PROCESSINSTID, PROCESSINSTNAME, PROCESSINSTDESC, CREATOR, OWNER, CURRENTSTATE, PRIORITY, RELATEDATA, RELATEDATAVCHR, LIMITNUM, LIMITNUMDESC, CREATETIME, STARTTIME, ENDTIME, FINALTIME, REMINDTIME, PARENTPROCID, PARENTACTID, PROCESSDEFID, ISTIMEOUT, TIMEOUTNUM, TIMEOUTNUMDESC, UPDATEVERSION, PROCESSDEFNAME, EXTEND1, EXTEND2, EXTEND3, EXTEND4, EXTEND5, EXTEND6, EXTEND7, CATALOGUUID, CATALOGNAME, TENANT_ID, BELONG, ALERTFLAG, ERRORFLAG, UPDATETIME FROM WFPROCESSINST WHERE PROCESSINSTID = PROINSTID;
				DELETE FROM WFPROCESSINST WHERE PROCESSINSTID = PROINSTID;
				
				--操作日志表 WF_H_OPTMSG
				INSERT INTO WF_H_OPTMSG (MESSAGEID, PRODUCER, RECEIVER, OPERATIONTYPE, CORRELATIONTYPE, CORRELATIONID, CONTANT, CREATETIME, PROCESSDEFID, PROCESSINSTID, ACTIVITYINSTID, WORKITEMID, TENANT_ID, EXTEND1, EXTEND2, EXTEND3, EXTEND4, EXTEND5 ) SELECT MESSAGEID, PRODUCER, RECEIVER, OPERATIONTYPE, CORRELATIONTYPE, CORRELATIONID, CONTANT, CREATETIME, PROCESSDEFID, PROCESSINSTID, ACTIVITYINSTID, WORKITEMID, TENANT_ID, EXTEND1, EXTEND2, EXTEND3, EXTEND4, EXTEND5  FROM WFOPTMSG WHERE PROCESSINSTID = PROINSTID;
				DELETE FROM WFOPTMSG WHERE PROCESSINSTID = PROINSTID;
				
				--参与者表 WF_H_WIPARTICIPANT
				INSERT INTO WF_H_WIPARTICIPANT (WIPARTICID, WORKITEMID, PARTICIPANTTYPE, PARTICIPANTID, PARTICIPANTNAME, PARTIINTYPE, DELEGATETYPE, PARTICIPANTINDEX, GLOBALID, WORKITEMNAME, WORKITEMTYPE, WORKITEMDESC, CURRENTSTATE, PARTICIPANT, PRIORITY, ISTIMEOUT, LIMITNUM, LIMITNUMDESC, CREATETIME, STARTTIME, ENDTIME, FINALTIME, REMINDTIME, ACTIONURL, PROCESSINSTID, ACTIVITYINSTID, STATESLIST, TIMEOUTNUM, TIMEOUTNUMDESC, PROCESSINSTNAME, ACTIVITYINSTNAME, PROCESSDEFID, PROCESSDEFNAME, PROCESSCHNAME, ACTIVITYDEFID, ASSISTANT, BIZSTATE, ALLOWAGENT, PARTINAME, ASSISTANTNAME, ROOTPROCINSTID, ACTIONMASK, URLTYPE, DEALRESULT, DEALOPINION, EXTEND1, EXTEND2, EXTEND3, EXTEND4, EXTEND5, EXTEND6, EXTEND7, CATALOGUUID, CATALOGNAME, TENANT_ID, ALERTFLAG, PRESSNUM, TASKPOOLID, BELONG, UPDATETIME, ACCEPTTIME) SELECT WIPARTICID, WORKITEMID, PARTICIPANTTYPE, PARTICIPANTID, PARTICIPANTNAME, PARTIINTYPE, DELEGATETYPE, PARTICIPANTINDEX, GLOBALID, WORKITEMNAME, WORKITEMTYPE, WORKITEMDESC, CURRENTSTATE, PARTICIPANT, PRIORITY, ISTIMEOUT, LIMITNUM, LIMITNUMDESC, CREATETIME, STARTTIME, ENDTIME, FINALTIME, REMINDTIME, ACTIONURL, PROCESSINSTID, ACTIVITYINSTID, STATESLIST, TIMEOUTNUM, TIMEOUTNUMDESC, PROCESSINSTNAME, ACTIVITYINSTNAME, PROCESSDEFID, PROCESSDEFNAME, PROCESSCHNAME, ACTIVITYDEFID, ASSISTANT, BIZSTATE, ALLOWAGENT, PARTINAME, ASSISTANTNAME, ROOTPROCINSTID, ACTIONMASK, URLTYPE, DEALRESULT, DEALOPINION, EXTEND1, EXTEND2, EXTEND3, EXTEND4, EXTEND5, EXTEND6, EXTEND7, CATALOGUUID, CATALOGNAME, TENANT_ID, ALERTFLAG, PRESSNUM, TASKPOOLID, BELONG, UPDATETIME, ACCEPTTIME FROM WFWIPARTICIPANT WHERE PROCESSINSTID = PROINSTID; 
				DELETE FROM WFWIPARTICIPANT WHERE PROCESSINSTID = PROINSTID;
				
				--BIZINFO
				INSERT INTO WF_H_BIZINFO (PROCESSINSTID, BIZTABLENAME, VCCOLUMN1, VCCOLUMN2, VCCOLUMN3, VCCOLUMN4, VCCOLUMN5, VCCOLUMN6, VCCOLUMN7, VCCOLUMN8, VCCOLUMN9, VCCOLUMN10, NMCOLUMN1, NMCOLUMN2, NMCOLUMN3, NMCOLUMN4, NMCOLUMN5, NMCOLUMN6, NMCOLUMN7, NMCOLUMN8, NMCOLUMN9, NMCOLUMN10, DTCOLUMN1, DTCOLUMN2, DTCOLUMN3, DTCOLUMN4, DTCOLUMN5, DTCOLUMN6, DTCOLUMN7, DTCOLUMN8, DTCOLUMN9, DTCOLUMN10) SELECT 	PROCESSINSTID, BIZTABLENAME, VCCOLUMN1, VCCOLUMN2, VCCOLUMN3, VCCOLUMN4, VCCOLUMN5, VCCOLUMN6, VCCOLUMN7, VCCOLUMN8, VCCOLUMN9, VCCOLUMN10, NMCOLUMN1, NMCOLUMN2, NMCOLUMN3, NMCOLUMN4, NMCOLUMN5, NMCOLUMN6, NMCOLUMN7, NMCOLUMN8, NMCOLUMN9, NMCOLUMN10, DTCOLUMN1, DTCOLUMN2, DTCOLUMN3, DTCOLUMN4, DTCOLUMN5, DTCOLUMN6, DTCOLUMN7, DTCOLUMN8, DTCOLUMN9, DTCOLUMN10 FROM WFBIZINFO WHERE PROCESSINSTID = PROINSTID;
				DELETE FROM WFBIZINFO WHERE PROCESSINSTID = PROINSTID;;
				
				--WF_H_NOTIFICATIONINST
				INSERT INTO WF_H_NOTIFICATIONINST (NOTIFICATIONID, TYPE, TITLE, SENDER, RECIPIENT, STATE, CREATETIME, CONFIRMTIME, FINALTIME, REMINDTIME, MESSAGE, ACTIONURL, PROCDEFID, PROCINSTID, ACTINSTID, WORKITEMID, PROCDEFNAME, PROCINSTNAME, ACTINSTNAME, WORKITEMNAME, TIMEOUTFLAG, REMINDEDFLAG, TENANT_ID, EXTEND1, EXTEND2, EXTEND3, EXTEND4, EXTEND5) SELECT NOTIFICATIONID, TYPE, TITLE, SENDER, RECIPIENT, STATE, CREATETIME, CONFIRMTIME, FINALTIME, REMINDTIME, MESSAGE, ACTIONURL, PROCDEFID, PROCINSTID, ACTINSTID, WORKITEMID, PROCDEFNAME, PROCINSTNAME, ACTINSTNAME, WORKITEMNAME, TIMEOUTFLAG, REMINDEDFLAG, TENANT_ID, EXTEND1, EXTEND2, EXTEND3, EXTEND4, EXTEND5 FROM WFNOTIFICATIONINST WHERE PROCINSTID = PROINSTID;
				DELETE FROM WFNOTIFICATIONINST WHERE PROCINSTID = PROINSTID;	
					
			END LOOP FETCH_LOOP;
			CLOSE C1;
		END @
		
